name = "Gambling"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47a971bc414f8f5e73848c9e3d502292e059cf3e58e6f7c0bd4267796a164621"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
