name = "Gambling"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db359bbf7289c34bd8ac82bf93ee30182c0f81a410b1643fe5510e718308c2e5"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
