name = "Gambling"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f04576617634c6f8e71210fde7fe5d72c437eb9ce504a00f4cb8773bc643e90f"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
